sonar.projectKey=JCPosso_nestjs-boilerplate
sonar.projectName=nestjs-boilerplate
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info
